FROM docker.io/fedora:latest

COPY staging/* /

RUN dnf update -y \
    && dnf install -y python3-dnf-plugin-local createrepo_c

ARG RPMS
RUN read -ra RPM_LIST <<< $RPMS;dnf install -y ${RPM_LIST[*]} \
    && dnf clean all
