ARG VARIANT=3.12-bookworm
FROM python:${VARIANT}


ARG NODEJS_VERSION='v22.12.0' \
    NODEJS_OS='linux' \
    NODEJS_ARCH='x64'

ARG NODEJS_PLATFORM="node-${NODEJS_VERSION}-${NODEJS_OS}-${NODEJS_ARCH}"

ARG NODEJS_URL="https://nodejs.org/dist/${NODEJS_VERSION}/${NODEJS_PLATFORM}.tar.xz"

ENV NODEJS_HOME="/opt/nodejs/${NODEJS_PLATFORM}"

RUN echo "************************* \${NODEJS_HOME}=$NODEJS_HOME/foo"
