
[build-system]
requires = [
    'cython > 3.1',
    'numpy >= 1.25',
    'pyarrow >= 12',
    'setuptools >= 75'
]
build-backend = 'setuptools.build_meta'

[project]
name = 'pfparsons-dnfopt'
version = '0.1.0'
description = 'Optimized OCI Images using DNF Package Management'
authors = [{ name = 'Patrick Parsons' }]
license-files = [ 'LICENSE' ]
readme = 'README.md'
dependencies = [
    'annotated_types'
]

[project.optional-dependencies]
dev = [
    'pytest',
    'pytest-cov'
]

[tool.pytest.ini_options]
pythonpath = [ 'src' ]
testpaths = [ 'src' ]

[project.scripts]
parquet_encrypt = "pfparsons.encryption_examples.parquet:main"
extension_test = "pfparsons.encryption_examples.parquet:test_ext"