FROM docker.io/fedora:latest
COPY staging/ /
ARG RPM_LIST
RUN --mount=type=bind,from=dnfcache,source=/var/cache/libdnf5,destination=/var/cache/libdnf5,rw \
    dnf update -y && dnf install -y ${RPM_LIST[*]}
