FROM docker.io/pfparsons/pfparsons-examples:fedora-base

ARG RPMS_1
RUN --mount=type=bind,from=dnfcache,source=/var/cache/libdnf5,destination=/var/cache/libdnf5,rw \
    [[ "${#RPMS_1}" -gt "0" ]] && dnf update -y && dnf install -y ${RPMS_1}

