#!/bin/bash
set -x
#
# DNF Local Cache for container builds
# Adapted from the following:
# - https://blog.holtzweb.com/posts/fedora-repository-local-mirror-over-LAN/
# - https://fedoramagazine.org/use-the-dnf-local-plugin-to-speed-up-your-home-lab/
# - https://www.redhat.com/en/blog/speeding-container-buildah
# bash script that creates a 'myfedora' image from fedora:latest.
# Adds dnf-local-plugin, points plugin to /srv/repodir for local
# repository and creates an external mount point for /srv/repodir
# that can be used with a -v switch in podman/docker


context_dir="$(dirname $(realpath $BASH_SOURCE))"

staging_dir="${context_dir}/staging"
mkdir -p "$staging_dir"

image_tag="docker.io/pfparsons/pfparsons-examples:devcontainer"
# alt registry.fedoraproject.org/fedora:latest
base_image="docker.io/pfparsons/pfparsons-examples:base"

# dnf-plugin config context and container paths
dnf_plugins_dir_container="/etc/dnf/plugins"
dnf_plugins_dir_context="${staging_dir}/${dnf_plugins_dir_container}"

mkdir -p "$dnf_plugins_dir_context"

dnf_local_plugin_filename="local.conf"
dnf_local_plugin_config_context="${dnf_plugins_dir_context}/${dnf_local_plugin_filename}"
dnf_local_plugin_config_container="${dnf_plugins_dir_container}/${dnf_local_plugin_filename}"

# container path of dnf-local-plugin repodir

dnf_local_plugin_fedora="/srv/dnf-local/fedora/latest"
dnf_local_plugin_repodir="${dnf_local_plugin_fedora}/repo"
dnf_local_plugin_cachedir="${dnf_local_plugin_fedora}/cache"


# Create dnf local plugin config file under context folder
cat <<EOF > "$dnf_local_plugin_config_context"
[main]
enabled = true
# Path to the local repository.
repodir = $dnf_local_plugin_repodir

# Createrepo options. See man createrepo_c
[createrepo]
# This option lets you disable createrepo command. This could be useful
# for large repositories where metadata is priodically generated by cron
# for example. This also has the side effect of only copying the packages
# to the local repo directory.
enabled = true

# If you want to speedup createrepo with the --cachedir option
# https://linux.die.net/man/8/createrepo
cachedir = $dnf_local_plugin_cachedir

# quiet = true
# verbose = false
EOF

# TODO: Automate docker.io login
podman pull $base_image

#start the build
container_id=$(buildah from $base_image)

# tag author
buildah config --author "pfparsons" "$container_id"

# install dnf-local-plugin, clean
buildah run "$container_id" -- dnf -y install python3-dnf-plugin-local createrepo_c
buildah run "$container_id" -- dnf -y clean all
# copy the generated plugin conf file from context to container
buildah copy "$container_id" "$dnf_local_plugin_config_context" "$dnf_local_plugin_config_container"

# mount the dnf local plugin repo and cache dirs
dnf_cache_image="docker.io/pfparsons/pfparsons-examples:dnf-cache"
buildah run "$container_id" --mount="type=bind,from=$dnf_cache_image",source=$dnf_local_plugin_repodir,target=$dnf_local_plugin_repodir
buildah run "$container_id" --mount="type=bind,from=$dnf_cache_image",source=$dnf_local_plugin_cachedir,target=$dnf_local_plugin_cachedir

readarray -t rpms < "$context_dir/rpm-list-test.txt"
buildah run "$container_id" -- dnf -y update
buildah run "$container_id" -- dnf -y install ${rpms[@]}
buildah run "$container_id" -- dnf -y clean all

# create myfedora image
buildah commit "$container_id" "$image_tag"

# clean up working image
buildah rm "$container_id"
