# [Choice] Python version (use -bookworm or -bullseye variants on local arm64/Apple Silicon): 3, 3.13, 3.12, 3.11, 3.10, 3.9, 3-bookworm, 3.13-bookworm, 3.12-bookworm, 3.11-bookworm, 3.10-bookworm, 3.9-bookworm, 3-bullseye, 3.13-bullseye, 3.12-bullseye, 3.11-bullseye, 3.10-bullseye, 3.9-bullseye, 3-buster, 3.12-buster, 3.11-buster, 3.10-buster, 3.9-buster
FROM docker.io/fedora:latest

COPY staging/* /

RUN --mount=type=bind,target=/srv/dnf-local-cache,source=/srv/dnf-local-cache,from=library/dnf-cache

RUN dnf update -y \
    && dnf install -y python3-dnf-plugin-local createrepo_c \
    && dnf install -y $RPMS\
    && dnf clean all

