FROM archlinux:base-devel
RUN pacman -Syyu --noconfirm \
    && pacman -Sy --noconfirm \
        git \
        curl \
        clang \
        gcc \
        cmake \
        ninja \
        python

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | /bin/bash -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"
