#!/bin/bash
set -x
#
# DNF Local Cache for container builds


##############################################################################
function init() {
    context_dir="$(dirname $(realpath $BASH_SOURCE))"
    staging_dir="${context_dir}/staging"

    local maybe_project_root="$context_dir"
    local maybe_scripts_dir

    while [[ -z "$BL_SCRIPTS_DIR" ]]
    do
        maybe_scripts_dir="$maybe_project_root/scripts"

        if [[ -d "$maybe_scripts_dir" ]] && [[ -r "$maybe_scripts_dir" ]]
        then # we found the scripts dir in the project root
            export BL_SCRIPTS_DIR="$maybe_scripts_dir"
            export BL_PROJECT_ROOT_DIR="$maybe_project_root"

        elif [[ "$maybe_project_root" == "/" ]]
        then # we traversed all the way to the fs root dir without success
            >&2 echo "ERROR: Unable to find scripts dir in any parent of " \
                     "$context_dir"

        else # try the parent dir 
            maybe_project_root="$(dirname $maybe_project_root)"
        fi
    done;

}



mkdir -p "$staging_dir"

image_repo="docker.io/pfparsons/pfparsons-examples"
pfp_base_image_tag="${image_repo}:base"
dnf_cache_image_tag="${image_repo}:dnf-cache"

# alt registry.fedoraproject.org/fedora:latest
base_image_tag="docker.io/fedora:latest"

# dnf-plugin config context and container paths
dnf_plugins_dir_container="/etc/dnf/plugins"
dnf_plugins_dir_context="${staging_dir}/${dnf_plugins_dir_container}"

mkdir -p "$dnf_plugins_dir_context"

dnf_local_plugin_filename="local.conf"
dnf_local_plugin_config_context="${dnf_plugins_dir_context}/${dnf_local_plugin_filename}"
dnf_local_plugin_config_container="${dnf_plugins_dir_container}/${dnf_local_plugin_filename}"

# container path of dnf-local-plugin repodir

dnf_local_plugin_fedora="/srv/dnf-local/fedora/latest"
dnf_local_plugin_repodir="${dnf_local_plugin_fedora}/repo"
dnf_local_plugin_cachedir="${dnf_local_plugin_fedora}/cache"


# Create dnf local plugin config file under context folder
cat <<EOF > "$dnf_local_plugin_config_context"
[main]
enabled = true
# Path to the local repository.
repodir = $dnf_local_plugin_repodir

# Createrepo options. See man createrepo_c
[createrepo]
# This option lets you disable createrepo command. This could be useful
# for large repositories where metadata is priodically generated by cron
# for example. This also has the side effect of only copying the packages
# to the local repo directory.
enabled = true

# If you want to speedup createrepo with the --cachedir option
# https://linux.die.net/man/8/createrepo
cachedir = $dnf_local_plugin_cachedir

# quiet = true
# verbose = false
EOF

# TODO: Automate docker.io login
podman pull $base_image_tag


# Base Image
##############################################################################

#start the build
container_id=$(buildah from $base_image_tag)

# tag author
buildah config --author "pfparsons" "$container_id"

# install dnf-local-plugin, clean
buildah run "$container_id" -- dnf -y install python3-dnf-plugin-local createrepo_c
buildah run "$container_id" -- dnf -y clean all

# copy the generated plugin conf file from context to container
buildah copy "$container_id" "$dnf_local_plugin_config_context" "$dnf_local_plugin_config_container"

# create the dnf local plugin repo and cache dirs
buildah run "$container_id" -- mkdir -p "$dnf_local_plugin_repodir"
buildah run "$container_id" -- mkdir -p "$dnf_local_plugin_cachedir"

# mark container repodir as a mount point for host volume
buildah config --volume "$dnf_local_plugin_repodir" "$container_id"
buildah config --volume "$dnf_local_plugin_cachedir" "$container_id"

# tag base image
buildah commit "$container_id" "$pfp_base_image_tag"

# clean up working image
buildah rm "$container_id"

# DNF Cache Image
##############################################################################

container_id=$(buildah from $pfp_base_image_tag)

# tag author
buildah config --author "pfparsons" "$container_id"

# install dnf-local-plugin, clean
buildah run "$container_id" -- dnf -y install python3-dnf-plugin-local createrepo_c
buildah run "$container_id" -- dnf -y clean all

# copy the generated plugin conf file from context to container
buildah copy "$container_id" "$dnf_local_plugin_config_context" "$dnf_local_plugin_config_container"

# create the dnf local plugin repo and cache dirs
buildah run "$container_id" -- mkdir -p "$dnf_local_plugin_repodir"
buildah run "$container_id" -- mkdir -p "$dnf_local_plugin_cachedir"

# make cache, update, and install rpms
buildah run "$container_id" -- dnf -y makecache
buildah run "$container_id" -- dnf -y update
rpm_list_file="$(realpath $context_dir/../rpm-list-test.txt)"
readarray -t rpms < "$rpm_list_file"
buildah run "$container_id" -- dnf -y install ${rpms[@]}

# tag base image
buildah commit "$container_id" "$dnf_cache_image_tag"

# clean up working image
buildah rm "$container_id"
