#!/bin/bash
#
# Various functions related to 


##############################################################################
# Write DNF Local Plugin configuration file to a filesystem

function dnf::write_local_plugin_config() {
    local output_file_path="${1:?}"
    local local_repo_dir="${2:?}"

    cat <<EOF > "$output_file_path"
[main]
enabled = true
# Path to the local repository.
repodir = $dnf_local_plugin_repodir

# Createrepo options. See man createrepo_c
[createrepo]
# This option lets you disable createrepo command. This could be useful
# for large repositories where metadata is priodically generated by cron
# for example. This also has the side effect of only copying the packages
# to the local repo directory.
enabled = true

# If you want to speedup createrepo with the --cachedir option
# https://linux.die.net/man/8/createrepo
cachedir = $local_repo_dir

# quiet = true
# verbose = false
EOF

}

